spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ss
    username: postgres
    password: ECSE321
  jpa:
    hibernate:
      ddl-auto: update
